import { StyleSheet } from 'react-native';
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0f0f23',
        padding: 24,
        paddingTop: 56,
    },
    backBtn: { marginBottom: 20 },
    backText: { color: '#6366f1', fontSize: 16 },
    title: {
        color: 'white',
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    subtitle: {
        color: '#888',
        fontSize: 13,
        marginBottom: 24,
    },
    nameCard: {
        backgroundColor: '#1e1b4b',
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#6366f1',
        marginBottom: 16,
    },
    nameLabel: {
        color: '#818cf8',
        fontSize: 12,
        marginBottom: 6,
    },
    nameValue: {
        color: 'white',
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 6,
    },
    nameHint: {
        color: '#666',
        fontSize: 12,
    },
    balanceCard: {
        backgroundColor: '#1a1a3e',
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#2a2a5e',
        marginBottom: 16,
    },
    balanceLabel: {
        color: '#888',
        fontSize: 12,
        marginBottom: 4,
    },
    balanceAmount: {
        color: 'white',
        fontSize: 32,
        fontWeight: 'bold',
    },
    statusCard: {
        backgroundColor: '#1a1a3e',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#2a2a5e',
        marginBottom: 16,
    },
    statusCardActive: {
        borderColor: '#22c55e',
        backgroundColor: '#052e16',
    },
    statusText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 14,
    },
    advertiseBtn: {
        backgroundColor: '#6366f1',
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
        marginBottom: 16,
    },
    advertiseBtnStop: {
        backgroundColor: '#7f1d1d',
    },
    advertiseBtnText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    paymentCard: {
        backgroundColor: '#052e16',
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#22c55e',
        marginBottom: 16,
    },
    paymentTitle: {
        color: '#22c55e',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 8,
    },
    paymentAmount: {
        color: '#22c55e',
        fontSize: 40,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    paymentFrom: {
        color: '#888',
        fontSize: 14,
    },
    infoBox: {
        backgroundColor: '#1a1a3e',
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: '#2a2a5e',
    },
    infoTitle: {
        color: 'white',
        fontWeight: 'bold',
        marginBottom: 10,
        fontSize: 15,
    },
    infoText: {
        color: '#888',
        lineHeight: 24,
        fontSize: 13,
    },
});