import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f0f23',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#0f0f23',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
  },
  loadingText: {
    color: '#888',
    fontSize: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 16,
  },
  greeting: {
    color: '#888',
    fontSize: 14,
  },
  username: {
    color: 'white',
    fontSize: 22,
    fontWeight: 'bold',
  },
  logoutBtn: {
    backgroundColor: '#1a1a3e',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ef4444',
  },
  logoutText: {
    color: '#ef4444',
    fontSize: 13,
  },
  statusPill: {
    marginHorizontal: 24,
    borderRadius: 12,
    padding: 12,
    marginBottom: 20,
  },
  btReceiveCard: {
    backgroundColor: '#1e1b4b',
    marginHorizontal: 24,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#6366f1',
    marginBottom: 12,
  },

  bankBtn: {
    backgroundColor: '#1e1b4b',
    marginHorizontal: 24,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#6366f1',
    marginBottom: 12,
  },
  bankBtnText: {
    color: '#818cf8',
    fontSize: 14,
    fontWeight: '600',
  },
  btReceiveText: {
    color: '#818cf8',
    fontSize: 15,
    fontWeight: '600',
  },
  statusText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '600',
  },
  balanceCard: {
    backgroundColor: '#6366f1',
    marginHorizontal: 24,
    borderRadius: 24,
    padding: 36,
    alignItems: 'center',
    marginBottom: 20,
  },
  balanceLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    marginBottom: 8,
  },
  balanceAmount: {
    color: 'white',
    fontSize: 52,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  balanceNote: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
  },
  syncWarning: {
    backgroundColor: '#92400e',
    marginHorizontal: 24,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    marginBottom: 16,
  },
  syncWarningText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 13,
  },
  actionsRow: {
    flexDirection: 'row',
    marginHorizontal: 24,
    gap: 12,
    marginBottom: 12,
  },
  actionCard: {
    flex: 1,
    backgroundColor: '#1a1a3e',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2a2a5e',
  },
  actionCardDisabled: {
    opacity: 0.5,
  },
  actionCardGreen: {
    backgroundColor: '#14532d',
    borderColor: '#166534',
  },
  actionIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  actionTitle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 4,
  },
  actionSub: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 11,
  },
  receiveCard: {
    backgroundColor: '#1a1a3e',
    marginHorizontal: 24,
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2a2a5e',
    marginBottom: 12,
  },
  receiveText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '600',
  },
  syncBtn: {
    marginHorizontal: 24,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#6366f1',
    marginBottom: 24,
  },
  syncBtnText: {
    color: '#6366f1',
    fontSize: 14,
    fontWeight: '600',
  },
  historySection: {
    marginHorizontal: 24,
    marginBottom: 40,
  },
  historyTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  emptyBox: {
    backgroundColor: '#1a1a3e',
    borderRadius: 20,
    padding: 40,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#2a2a5e',
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  emptyText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  emptySub: {
    color: '#888',
    fontSize: 13,
    textAlign: 'center',
  },
  txnRow: {
    backgroundColor: '#1a1a3e',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#2a2a5e',
  },
  txnLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  txnIcon: {
    fontSize: 28,
  },
  txnName: {
    color: 'white',
    fontWeight: '600',
    marginBottom: 2,
  },
  txnDate: {
    color: '#666',
    fontSize: 11,
    marginBottom: 2,
  },
  txnStatus: {
    color: '#888',
    fontSize: 11,
  },
  txnAmount: {
    fontWeight: 'bold',
    fontSize: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#1a1a3e',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 32,
    borderWidth: 1,
    borderColor: '#2a2a5e',
  },
  modalTitle: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 6,
  },
  modalSub: {
    color: '#888',
    fontSize: 13,
    marginBottom: 24,
  },
  modalInput: {
    backgroundColor: '#0f0f23',
    borderRadius: 14,
    padding: 18,
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
    borderWidth: 1,
    borderColor: '#2a2a5e',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalButton: {
    backgroundColor: '#6366f1',
    borderRadius: 14,
    padding: 18,
    alignItems: 'center',
    marginBottom: 12,
  },
  modalButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalCancel: {
    padding: 16,
    alignItems: 'center',
  },
  modalCancelText: {
    color: '#888',
    fontSize: 15,
  },
  cashoutBtn: {
    marginHorizontal: 24,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ef4444',
    marginBottom: 24,
  },
  cashoutBtnText: {
    color: '#ef4444',
    fontSize: 14,
    fontWeight: '600',
  },
});

export default styles;